portal/routes/web.php
<?php

use App\Http\Controllers\Admin\AdminAgentsController;
use App\Http\Controllers\Admin\AdminClaimsController;
use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\Admin\AdminNotificationsController;
use App\Http\Controllers\Admin\AdminPoliciesController;
use App\Http\Controllers\Admin\AdminReportsController;
use App\Http\Controllers\Agent\AgentCommisionsController;
use App\Http\Controllers\Agent\AgentDashboardController;
use App\Http\Controllers\Agent\AgentPoliciesController;
// use App\Http\Controllers\Agent\videoTutsController;
use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ClaimController;
use App\Http\Controllers\Clients\BeneficieryController;
use App\Http\Controllers\Clients\ClaimsController;
use App\Http\Controllers\Clients\PaymentController;
use App\Http\Controllers\Clients\PoliciesController;
use App\Http\Controllers\Clients\ProfileController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PolicyController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PackagesController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Agent\VideoTutsController;


// use App\Http\Controllers\Agent\AgentCommisionsController;
// use App\Http\Controllers\Agent\AgentDashboardController;
// use App\Http\Controllers\Agent\AgentPoliciesController;
use App\Http\Controllers\Agent\AgentProfileController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;

// use App\Http\Controllers\Admin\AdminPoliciesController;
// use App\Http\Controllers\Admin\AdminAgentsController;
// use App\Http\Controllers\Admin\AdminClaimsController;
// use App\Http\Controllers\Admin\AdminDashboardController;
// use App\Http\Controllers\Admin\AdminNotificationsController;
// use App\Http\Controllers\Admin\AdminReportsController;
use App\Http\Controllers\Admin\AdminProfileController;
use App\Http\Controllers\Admin\PolicyPlanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return view('welcome');
});
//website_routes
Route::get('portal',[PortalController::class, 'index'])->name('portal');
Route::get('claims',[ClaimController::class, 'index'])->name('claims');
Route::get('myPolicy',[PolicyController::class, 'index'])->name('myPolicy');
Route::get('contact',[ContactController::class, 'index'])->name('contact');
Route::post('contactUs',[ContactController::class, 'sendMessage'])->name('contactUs');
Route::post('call_back',[ContactController::class, 'calls'])->name('call_back');
Route::get('applications',[ApplicationController::class, 'index'])->name('applications');
Route::get('stepper_application',[ApplicationController::class, 'application'])->name('stepper_application');
Route::get('policy_products/cash_funerals',[PackagesController::class, 'cashFunerals'])->name('policy_products/cash_funerals');
Route::get('policy_products/cremations',[PackagesController::class, 'cremations'])->name('policy_products/cremations');
Route::get('policy_products/funeral_arrangements',[PackagesController::class, 'funeralArrangements'])->name('policy_products/funeral_arrangements');



Route::get('policy_products/funeral_policies',[PackagesController::class, 'funeralPolicies'])->name('policy_products/funeral_policies');
Route::post('filterCover',[PackagesController::class, 'funeralPolicies'])->name('filterCover');

Route::get('policy_products/tombstones',[PackagesController::class, 'tombstones'])->name('policy_products/tombstones');

//portal_routes
Route::get('admin/policy-stepper',[AdminPoliciesController::class, 'application'])->name('admin/policy-stepper');
Route::get('stepper-application',[ApplicationController::class, 'adminMail'])->name('stepper-application');
Route::post('admin-mail',[ApplicationController::class, 'adminMail'])->name('admin-mail');
Route::post('agent-mail',[AgentPoliciesController::class, 'agentMail'])->name('agent-mail');
Route::get('agent-policy',[AgentPoliciesController::class, 'agentPolicy'])->name('agent-policy');
Route::post('upload-video',[VideoTutsController::class, 'store'])->name('upload-video');

Auth::routes(['verify' => true]);
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('products', ProductController::class);
});


//client_routes
Route::get('clients/policy',[PoliciesController::class, 'index'])->name('clients/policy');
Route::post('clients/add-beneficiary',[PoliciesController::class, 'new_benefiary'])->name('clients/add-beneficiary');
Route::post('clients/update-beneficiary',[PoliciesController::class, 'beneficiary_update'])->name('clients/update-beneficiary');
Route::post('clients/add-spouse',[PoliciesController::class, 'new_spouse'])->name('clients/add-spouse');
Route::get('clients/beneficiary_details/{id}',[PoliciesController::class, 'beneficiary_details'])->name('clients/beneficiary_details');
Route::get('clients/delete_beneficiary/{id}',[PoliciesController::class, 'delete_beneficiary'])->name('clients/delete_beneficiary');
Route::get('clients/beneficiaries',[BeneficieryController::class, 'index'])->name('clients/beneficiaries');
Route::get('clients/spouse_details/{id}',[PoliciesController::class, 'spouse_details'])->name('clients/spouse_details');
Route::post('clients/update-spouse',[PoliciesController::class, 'spouse_update'])->name('clients/update-spouse');
Route::get('clients/delete_spouse/{id}',[PoliciesController::class, 'delete_spouse'])->name('clients/delete_spouse');
Route::post('clients/update_holder',[PoliciesController::class, 'holder_update'])->name('clients/update_holder');
Route::get('clients/payments',[PaymentController::class, 'index'])->name('clients/payments');
Route::get('clients/profile',[ProfileController::class, 'index'])->name('clients/profile');
Route::get('clients/claims',[ClaimsController::class, 'index'])->name('clients/claims');
Route::get('clients/claim_details/{id}',[ClaimsController::class, 'getClaimDetails'])->name('clients/claim_details');
Route::get('clients/claimForm',[ClaimsController::class, 'getClaimForm'])->name('clients/claimForm');
Route::post('clients/claimForm',[ClaimsController::class, 'captureClaims'])->name('claims.store');

//agent_routes
Route::get('agents/dashboard',[AgentDashboardController::class, 'index'])->name('agents/dashboard');
Route::get('agents/policy',[AgentPoliciesController::class, 'index'])->name('agents/policy');
Route::get('agents/create_policy',[AgentPoliciesController::class, 'createPolicy'])->name('agents/create_policy');
Route::get('agents/policy_details/{id}',[AgentPoliciesController::class, 'showPolicy'])->name('agents/policy_details');
Route::get('agents/commissions',[AgentCommisionsController::class, 'index'])->name('agents/commissions');
Route::get('agents/profile',[AgentProfileController::class, 'index'])->name('agents/profile');
//demo
Route::get('agents/tutorials',[videoTutsController::class, 'tuts'])->name('agents/tutorials');
Route::post('search-tutorials',[videoTutsController::class, 'tutSearch'])->name('search-tutorials');
Route::get('clear-search',[videoTutsController::class, 'clrSearch'])->name('clear-search');



Route::get('register',[RegisterController::class, 'index'])->name('register');
Route::get('login',[LoginController::class, 'index'])->name('login');

//admin_routes
Route::get('admin/dashboard',[AdminDashboardController::class, 'index'])->name('admin/dashboard');
//policy plans
Route::get('admin/policy_plans',[PolicyPlanController::class, 'index'])->name('admin/policy_plans');
Route::post('capturePlans',[PolicyPlanController::class, 'capturePlans'])->name('capturePlans');
Route::get('admin/delete_plan/{id}',[PolicyPlanController::class, 'deletePlan'])->name('admin/delete_plan');
Route::post('admin/update_plan',[PolicyPlanController::class, 'updatePlan'])->name('admin/update_plan');

Route::get('admin/policies',[AdminPoliciesController::class, 'index'])->name('admin/policies');
Route::get('admin/agents',[AdminAgentsController::class, 'index'])->name('admin/agents');
Route::get('admin/claims',[AdminClaimsController::class, 'index'])->name('admin/claims');
Route::get('admin/claims/view-claims/{id}',[AdminClaimsController::class, 'viewClaim'])->name('admin/claims/view-claims');
Route::post('claim-filter',[AdminClaimsController::class, 'filterByDate'])->name('claim-filter');
Route::get('admin/delete-agent/{id}',[AdminAgentsController::class, 'deleteAgent'])->name('admin/delete-agent');
Route::get('admin/view-agent/{id}',[AdminAgentsController::class, 'viewAgent'])->name('admin/view-agent');

Route::post('agent-search',[AdminAgentsController::class, 'filterByAgent'])->name('agent-search');
Route::get('admin/reports',[AdminReportsController::class, 'index'])->name('admin/reports');
Route::get('admin/notifications',[AdminNotificationsController::class, 'index'])->name('admin/notifications');
Route::get('admin/profile',[AdminProfileController::class, 'index'])->name('admin/profile');
Route::post('policy-filter',[AdminPoliciesController::class, 'filterByDate'])->name('policy-filter');
Route::get('clear-policy-search',[AdminPoliciesController::class, 'clrSearch'])->name('clear-policy-search');
Route::get('clear-search',[AdminAgentsController::class, 'clrSearch'])->name('clear-search');

portal/resources/views/admin/addVideo.blade.php
@extends('layouts.portalMaster')

@section('content')


    <div class="page-wrapper">
        <div class="content container-fluid">

            <div class="page-header">
                <div class="row">
                    <div class="col">
                        <h3 class="page-title">Add a Tutorial</h3>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url('/home') }}">Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="{{ url('admin/tutorials') }}">Video Tutorials</a></li>
                            <li class="breadcrumb-item active">Add Tutorials</li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">

                    <div class="profile-menu">
                    <form method="post" action="{{ route('admin/add-video') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="title">Title</label>
                            <input type="hidden"  class="form-control" id="id" name="id" placeholder="Video Title" style="background-color: #F5F5F5;color: black">
                            <input type="text"  class="form-control" id="title" name="title" placeholder="Video Title" style="background-color: #F5F5F5;color: black">
                        </div>

                        <div class="form-group">
                            <label for="file">Video</label>
                            <input type="file" class="form-control" id="file" name="file"   style="background-color: #F5F5F5;color: black">
                        </div>
                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea class="form-control" name="description" id="description" placeholder="Video Description"></textarea>
                        </div>

                        <div class="form-group">

                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

portal/resources/views/admin/agents.blade.php
@extends('layouts.portalMaster')

@section('content')
    <div class="page-wrapper">

        <div class="content container-fluid">

            <div class="page-header">
                <div class="row">
                    <div class="col">
                        <h3 class="page-title">Agents</h3>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href=". url('/home') .">Dashboard</a></li>
                            <li class="breadcrumb-item active">Agents</li>
                        </ul>
                    </div>
                    <div class="col-auto text-right">
                        <a class="btn btn-light filter-btn" href="{{ url('clear-search') }}" data-toggle="tooltip" title="Clear Search">
                            <i class="fas fa-times"></i>
                        </a>
                        <a class="btn btn-white filter-btn" href="javascript:void(0);" id="filter_search" data-toggle="tooltip" title="Search Agent">
                            <i class="fas fa-filter"></i>
                        </a>
                        <a href="{{ route('users.create') }}" class="btn btn-primary add-button ml-3" data-toggle="tooltip" title="Add New Agent">
                            <i class="fas fa-plus"></i>
                        </a>
                    </div>
                </div>
            </div>

            <div class="card filter-card" id="filter_inputs">
                <div class="card-body pb-0">
                    <form method="POST" action="{{route('agent-search') }}"  enctype="multipart/form-data"/>
                    @CSRF
                        <div class="row filter-row">
                            <div class="col-sm-6 col-md-6">
                                <div class="form-group">
                                    <label class="col-form-label">Search for an Agent(s)</label>
                                    <input class="form-control" name="agents" type="text">
                                </div>
                            </div>

                            <div class="col-sm-6 col-md-3">

                                <div class="form-group">
                                    <button class="btn btn-primary btn-block" type="submit">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <ul class="nav nav-tabs menu-tabs">
                <li class="nav-item active">
                    <a class="nav-link" data-toggle="tab" href="#all_agents">All Agents <span class="badge badge-primary">{{ $allagents1}}</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#active_agents">Active Agents <span class="badge badge-primary">{{ $activeAgents}}</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#inactive_agents">InActive Agents <span class="badge badge-primary">{{ $inactiveAgents1}}</span></a>
                </li>


            </ul>

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="tab-content profile-tab-cont">
                                <div class="table-responsive tab-pane show active" id="all_agents">
                                    <table class="table table-hover table-center mb-0 datatable">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Image</th>
                                            <th>Fullname</th>
                                            <th>Email</th>
                                            <th>Mobile</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($agents as $Agents)
                                        <tr>
                                            <td>{{ $Agents->id }}</td>
                                            <td>
                                                <a href="service-details.html">
                                                    <img class="rounded service-img mr-1" src="asset('storage/app/public/images/avatars/'.$Agents->image" alt="">
                                                </a>
                                            </td>
                                            <td>{{ $Agents->name }}</td>
                                            <td>{{ $Agents->email }}</td>
                                            <td>{{ $Agents->mobile}}</td>
                                            <td class="text">{{ $Agents->status }}
                                                {{-- // .-- <div class="status-toggle">
                                                //     <input id="service_1" class="check" type="checkbox">
                                                //     <label for="service_1" class="checktoggle">. $Agents->status.</label>
                                                // </div> --. --}}
                                            </td>
                                            <td>
                                                <a href="{{ url('admin/view-agent/'.$Agents->id) }}" class="btn btn-info ">
                                                    <i class="far fa-eye mr-1"></i> View
                                                </a>
                                                <a href="{{ url('admin/delete-agent/'.$Agents->id) }}" class="btn btn-danger">
                                                <i class="far fa-trash-alt"></i> Delete
                                                </a>
                                            </td>
                                        </tr>
                                        @endforeach
                                        {!! $agents->links() !!}

                                        </tbody>
                                    </table>
                                </div>

                                <div class="table-responsive tab-pane fade" id="active_agents">
                                    <table class="table table-hover table-center mb-0 datatable">
                                        <thead>
                                       <tr>
                                            <th>#</th>
                                            <th>Image</th>
                                            <th>Fullname</th>
                                            <th>Email</th>
                                            <th>Mobile</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($activeAgents1 as $activeagents1)
                                        <tr>
                                            <td>{{ $activeagents1->id }}</td>
                                            <td>
                                                <a href="service-details.html">
                                                    <img class="rounded service-img mr-1" src="asset('storage/app/public/images/avatars/'.$activeagents1->image" alt="">
                                                </a>
                                            </td>
                                            <td>{{ $activeagents1->name }}</td>
                                            <td>{{ $activeagents1->email }}</td>
                                            <td>{{ $activeagents1->mobile}}</td>
                                            <td class="text">{{ $activeagents1->status }}
                                                {{-- // .-- <div class="status-toggle">
                                                //     <input id="service_1" class="check" type="checkbox">
                                                //     <label for="service_1" class="checktoggle">. $Agents->status.</label>
                                                // </div> --. --}}
                                            </td>
                                            <td>
                                                <a href=". url('admin/claims/view-claims/'.$claims->id) ." class="btn btn-info ">
                                                    <i class="far fa-eye mr-1"></i> View
                                                </a>
                                                <a href=". url('admin/claims/view-claims/'.$claims->id) ." class="btn btn-danger">
                                                <i class="far fa-trash-alt"></i> Delete
                                                </a>
                                            </td>
                                        </tr>
                                        @endforeach
                                        {!! $activeAgents1->links() !!}

                                        </tbody>
                                    </table>
                                </div>

                                <div class="table-responsive tab-pane fade" id="inactive_agents">
                                    <table class="table table-hover table-center mb-0 datatable">
                                        <thead>
                                       <tr>
                                            <th>#</th>
                                            <th>Image</th>
                                            <th>Fullname</th>
                                            <th>Email</th>
                                            <th>Mobile</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($inactiveAgents as $inactiveagents1)
                                        <tr>
                                            <td>{{ $inactiveagents1->id }}</td>
                                            <td>
                                                <a href="service-details.html">
                                                    <img class="rounded service-img mr-1" src="asset('storage/app/public/images/avatars/'.$inactiveagents1->image" alt="">
                                                </a>
                                            </td>
                                            <td>{{ $inactiveagents1->name }}</td>
                                            <td>{{ $inactiveagents1->email }}</td>
                                            <td>{{ $inactiveagents1->mobile}}</td>
                                            <td class="text">{{ $inactiveagents1->status }}
                                                {{-- // .-- <div class="status-toggle">
                                                //     <input id="service_1" class="check" type="checkbox">
                                                //     <label for="service_1" class="checktoggle">. $Agents->status.</label>
                                                // </div> --. --}}
                                            </td>
                                            <td>
                                                <a href=". url('admin/claims/view-claims/'.$claims->id) ." class="btn btn-info ">
                                                    <i class="far fa-eye mr-1"></i> View
                                                </a>
                                                <a href=". url('admin/claims/view-claims/'.$claims->id) ." class="btn btn-danger">
                                                <i class="far fa-trash-alt"></i> Delete
                                                </a>
                                            </td>
                                        </tr>
                                        @endforeach
                                        {!! $inactiveAgents->links() !!}

                                        </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

portal/resources/views/admin/notifications.blade.php
@extends('layouts.portalMaster')

@section('content')

@endsection

portal/resources/views/admin/reports.blade.php
@extends('layouts.portalMaster')

@section('content')

@endsection

portal/resources/views/admin/video.blade.php
@extends('layouts.portalMaster')

@section('content')
    <div class="page-wrapper">
        <div class="content container-fluid">

            <div class="page-header">
                <div class="row">
                    <div class="col">
                        <h3 class="page-title">Video Tutorials</h3>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url('/home') }}">Dashboard</a></li>
                            <li class="breadcrumb-item active">Video Tutorials</li>
                        </ul>
                    </div>
                    <div class="col-auto text-right">
                        <a class="btn btn-light filter-btn" href="{{ url('admin/clear-search') }}" data-toggle="tooltip" title="Clear Search">
                            <i class="fas fa-times"></i>
                        </a>
                        <a class="btn btn-white filter-btn" href="javascript:void(0);" id="filter_search" data-toggle="tooltip" title="Search">
                            <i class="fas fa-filter"></i>
                        </a>
                        <a href="{{url('admin/addvideo')}}" class="btn btn-primary add-button ml-3" data-toggle="tooltip" title="Add New Video">
                            <i class="fas fa-plus"></i>
                        </a>
                    </div>
                </div>
            </div>

            <div class="card filter-card" id="filter_inputs">
                <div class="card-body pb-0">
                    <form method="POST" action="{{ route('admin/search-video')}}"  enctype="multipart/form-data"/>
                    @CSRF
                    <div class="row filter-row" >

                        <div class="col-sm-12">
                        <div class="input-group">
                            <div class="form-outline">
                              <input type="search" id="form1" class="form-control" name="searchItem" style="width:300px" placeholder="Enter Video title..."/><br>
                              {{-- <label class="form-label" for="form1">Search</label> --}}
                            </div>
                            <button type="submit" class="btn btn-primary" style="width: 100px">
                              <i class="fas fa-search"></i>
                            </button>
                          </div>
                        </div>
                    </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            {!! $video->links() !!}
                            <div class="tab-content profile-tab-cont">
                                <div class="table-responsive tab-pane show active" id="all_polices">
                                    <table class="table table-hover table-center mb-0 datatable">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Video</th>
                                            <th>Title</th>
                                            <th>Description</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                @foreach($video as $v)
                                    <tr>
                                        <td>{{ $v->id}}</td>
                                        <td>
                                            <video  width="70" height="70" controlsList="nodownload">
                                                <source src="{{ asset('storage/app/public/video/'.$v->video) }}" type="video/mp4">
                                            </video>
                                        </td>

                                        <td>{{ $v->title }}</td>
                                        <td>{{ $v->description }}</td>
                                        <td>
                                            <a href="{{ url('admin/show-video/'.$v->id) }}" class="btn btn-info">
                                                <i class="far fa-eye mr-1"></i> View
                                            </a>
                                            <a href="{{ url('admin/delete-video/'.$v->id) }}" class="btn btn-danger">
                                                <i class="far fa-trash-alt"></i> Delete
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div><br>
                            {!! $video->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>